---
# tasks file for ansible-timezone
- name: main | configuring /etc/localtime
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: "/etc/localtime"
    state: "link"
    # We force this in order to overwrite the destination if it is a file vs.
    # a symlink
    force: yes
  tags:
    - configuration
    - timezone

- name: main | configuring /etc/timezone
  template:
    src: "timezone.j2"
    dest: "/etc/timezone"
  notify: update tzdata
  when: ansible_os_family == "Debian"
  tags:
    - configuration
    - timezone
